name: magnus-voice-assistant

services:
  magnus-voice-postgres:
      image: postgres
      restart: always
      command: -p 5435
      env_file:
        - .env
      expose: 
        - 5435
      ports:
        - 5435:5435
      volumes:
        - magnus_voice_postgres_data:/var/lib/postgresql/data/
      
  magnus-voice-backend:
    image: magnus_voice_backend
    container_name: magnus_voice_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    restart: always

  redis-celery-broker:
    image: redis:alpine
    container_name: redis_celery_broker
    ports:
      - 6379:6379
    volumes:
      - redis_celery_broker_data:/data


volumes:
  magnus_voice_postgres_data:
  redis_celery_broker_data:

